In [1]:
import pandas as pd
df=pd.read_csv("train_and_test2.csv")
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,survived
0,1,22.0,7.2500,0,1,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,...,0,0,0,3,0,0,2.0,0,0,0

In [4]:
target=df.survived

In [5]:
inputs=df.drop('survived',axis='columns')

In [7]:
inputs.columns[inputs.isna().any()]

Index(['Embarked'], dtype='object')

In [8]:
inputs.Embarked=inputs.Embarked.fillna(inputs.Embarked.mean())

In [10]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(inputs,target,test_size=0.25)

In [11]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(xtrain,ytrain)

GaussianNB()

In [12]:
xtest[:10]

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,...,zero.11,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18
909,910,27.0,7.9250,1,1,0,0,0,0,0,...,0,0,0,0,3,0,0,2.0,0,0
977,978,27.0,7.8792,1,0,0,0,0,0,0,...,0,0,0,0,3,0,0,1.0,0,0
809,810,33.0,53.1000,1,1,0,0,0,0,0,...,0,0,0,0,1,0,0,2.0,0,0
318,319,31.0,164.8667,1,0,0,0,0,0,0,...,0,0,0,0,1,0,0,2.0,0,0
357,358,38.0,13.0000,1,0,0,0,0,0,0,...,0,0,0,0,2,0,0,2.0,0,0
997,998,21.0,7.8208,0,0,0,0,0,0,0,...,0,0,0,0,3,0,0,1.0,0,0
1238,1239,38.0,7.2292,1,0,0,0,0,0,0,...,0,0,0,0,3,0,0,0.0,0,0
336,337,29.0,66.6000,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,2.0,0,0
1193,1194,43.0,21.0000,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,2.0,0,0
149,150,42.0,13.0000,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,2.0,0,0

In [13]:
ytest[:10]

909     0
977     0
809     1
318     1
357     0
997     0
1238    0
336     0
1193    0
149     0
Name: survived, dtype: int64

In [14]:
model.predict(xtest[:10])

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0], dtype=int64)

In [15]:
model.predict_proba(xtest[:10])

array([[0.8896686 , 0.1103314 ],
       [0.91349629, 0.08650371],
       [0.51458613, 0.48541387],
       [0.01648565, 0.98351435],
       [0.41851735, 0.58148265],
       [0.9886443 , 0.0113557 ],
       [0.98229423, 0.01770577],
       [0.61564424, 0.38435576],
       [0.99688417, 0.00311583],
       [0.84944856, 0.15055144]])